### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by xinzheli628** [Binance-docs/binance-futures-connector-python#14]
when I try to run 
"from binance.futures import Futures 
client = Futures()
print(client.time())"

I always get problem like 
<img width="1252" alt="WX20220225-113527@2x" src="https://user-images.githubusercontent.com/28423098/155648890-67f35a00-8b7e-481b-86d7-df318e8a48d6.png">

**Comment by 2pd** [comment]
please check if you have any issue of connecting to the api server.  try to use curl for debug.


`curl "https://fapi.binance.com/fapi/v1/time"`
