### ISSUE TITLE
How to setup proxy

### ISSUE THREAD

**Issue by AngLi666** [Binance-docs/binance-futures-connector-python#17]
<img width="1252" alt="155648890-67f35a00-8b7e-481b-86d7-df318e8a48d6" src="https://user-images.githubusercontent.com/77546516/156886017-f2321483-c1ce-460f-b473-1d3516b6cbd5.png">

IP from China got blocked. A connection error is returned when connect to binance, for example, https://fapi.binance.com/fapi/v1/time. The weblink is accessible through a VPN. But the python code does not work.

I tried to setup a proxy, using IP from Japan, Russia, India, Korea, Brazil. None of them works.
Could you please give a successful example of how to correctly use proxy settings?

You can use the free proxy resource from https://www.proxynova.com/proxy-server-list/
You can also use my VPN node, 
ip：31.v2yd2.poronode.top
port：16857
encode：aes-256-cfb
protocal：auth_aes128_md5
protocal param：20810:n0FbrRQEFd1o
ofs：tls1.2_ticket_auth
ofs param：eefaa20810.microsoft.com
passwd: private msg. Discord: iAaron#6598

**Comment by andrea-c-binance** [comment]
@AngLi666 we have update the proxy info: https://github.com/Binance-docs/binance-futures-connector-python/blob/main/README.md#proxy, please give it a try and let us know if any issue, thanks!
