### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by edo1000** [Binance-docs/binance-futures-connector-python#21]
No filter order open and cancel order.

**Comment by andrea-c-binance** [comment]
@edo1000 you can filter the orders by order ID

**Comment by edo1000** [comment]
To cancel the order, I could not.
what procedure to search ID and cancel the order?

**Comment by 2pd** [comment]
query order, https://github.com/Binance-docs/binance-futures-connector-python/blob/main/examples/futures/trade/get_order.py

cancel order, https://github.com/Binance-docs/binance-futures-connector-python/blob/main/examples/futures/trade/cancel_order.py
