### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by sabershariat20** [Binance-docs/binance-futures-connector-python#22]
Hello . 
How can i enable testnet ?

**Comment by 2pd** [comment]
you can initial the client instance and setting the base_url to the Client:


```python

client = Client(key, secret, base_url="https://testnet.binancefuture.com")

```

Then you could call most of the methods in the library, but the request will be sent to testnet.


An example file that shows how to set the base_url:
https://github.com/Binance-docs/binance-futures-connector-python/blob/main/examples/futures/trade/new_order.py#L12
