### ISSUE TITLE
cancel_order doesn't work 

### ISSUE THREAD

**Issue by goatz-dev** [Binance-docs/binance-futures-connector-python#23]
I try to close an order just after i created it to test the method on the base_url="https://testnet.binancefuture.com"
but i have the following issue : 
File "D:\Logiciels\Python\lib\site-packages\binance\futures\account.py", line 268, in cancel_order
    return self.sign_request("DELETE", url_path, params)
  File "D:\Logiciels\Python\lib\site-packages\binance\api.py", line 84, in sign_request
    return self.send_request(http_method, url_path, payload, special)
  File "D:\Logiciels\Python\lib\site-packages\binance\api.py", line 118, in send_request
    self._handle_exception(response)
  File "D:\Logiciels\Python\lib\site-packages\binance\api.py", line 171, in _handle_exception
    raise ClientError(status_code, err["code"], err["msg"], response.headers)
binance.error.ClientError: (400, -2011, 'Unknown order sent.', {'Content-Type': 'application/json', 'Content-Length': '42', 'Connection': 'keep-alive', 'Date': 'Tue, 12 Apr 2022 16:28:13 GMT', 'Server': 'Bengine', 'X-MBX-USED-WEIGHT-1M': '2', 'x-response-time': '3ms', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 e832b62df62ac7dea0463212e63d91f6.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'CDG50-P2', 'X-Amz-Cf-Id': 'HHB4Beib98-164R-Sp-TL_K8MBoDIk_bLYztkzbND6AF9mg2mmeX2w=='})

my cancel_order method call is here : 
clientData.cancel_order(
        symbol="BTCUSDT",
        orderId = orderIdOpen)
where orderIdOpen is a var i get from the new_order method's result

**Comment by 2pd** [comment]
from the error message, it's said the order is not found as in open status, the reasons could be:

- order is not found in this account
- order is found, but not able to cancel:
  - order is cancelled
  - order is filled
  - order is expired
  - etc

**Comment by goatz-dev** [comment]
Hi thanks for the answer. Unfortunately i create the order just before and i take back the orderId . I don’t know if it can help but i use my test account on the testnet future

**Comment by goatz-dev** [comment]
I have an update i think it's because i used the new_order_test method

**Comment by cuongnm306** [comment]
go to pure cancel_order function, change 'orderId is None' to 'orderId is not None'
