### ISSUE TITLE
What are id and callback ?

### ISSUE THREAD

**Issue by goatz-dev** [Binance-docs/binance-futures-connector-python#27]
Hi, in the file [https://github.com/Binance-docs/binance-futures-connector-python/blob/main/examples/websocket/futures/liquidation_order.py](url) you write : 
`id= 13
callback = message_handler`
I don't understand what these are and how to connect to testnet to my api.
Moreover, I try to autoclose an order when an order is close( ex : a Stop loss is closed but the take profit isn't canceled so i do i in code) and i don't know if that's the correct method to use.

**Comment by 2pd** [comment]
server will return this id when subscription is accomplished.

For the callback, it's nothing special.  When message is received, this callback method will be triggered, so it's the place you can define your method to process those messages.
