### ISSUE TITLE
Stop-limit order not working properly

### ISSUE THREAD

**Issue by RogueCodiac** [Binance-docs/binance-futures-connector-python#6]
Whenever I try to place a stop-limit order using:

_**client = Client(api_key="key", api_secret="secret")

client.futures_create_order(**dict(
            symbol="BTCUSDT",
            quantity=0.02,
            stopPrice=50000,  # As of writing this the price of BTC is ≈51000
            price=40000,
            side="BUY",
            positionSide="LONG",
            type="STOP",
            timeInForce="GTC,
            newOrderRespType="FULL"
))
**_

I get the following error:

Traceback (most recent call last):
  File "/Users/yamansirajaldeen/Documents/Gismo_0/OrderPlacer.py", line 117, in <module>
    print(client.open_long_stop_limit("BTC", 0.02, stopPrice=50000, price=40000))
  File "/Users/yamansirajaldeen/Documents/Gismo_0/OrderPlacer.py", line 98, in open_long_stop_limit
    result: dict = self.futures_create_order(**dict(
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 5852, in futures_create_order
    return self._request_futures_api('post', 'order', True, data=params)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 339, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 315, in _request
    return self._handle_response(self.response)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-2021): Order would immediately trigger.

However, when I enter the same order on the application manually it works:

<img width="860" alt="Screen Shot 2021-12-25 at 9 06 33 AM" src="https://user-images.githubusercontent.com/88580314/147379545-fa4d9d12-ce7b-4b58-aee6-80dc1dbd9d83.png">

**Comment by kirankumarbiradar** [comment]
`from binance.futures import Futures
client = Futures()

api_key = "xxxx"
api_secret ="xxx"
pairs = "LTCUSDT"
quentity = 0.5

client = Futures(key=api_key, secret=api_secret)
order = client.new_order

current_price = 150.01
stop_price = 145.01
take_profit_price = 155.01
#stop market
params = {
    "symbol": pairs,
    "side": "SELL",
    "type": "STOP_MARKET",
    "quantity": quentity,
    "timeInForce": "GTC", 
    "stopPrice":stop_price,
    "closePosition":"STOP_MARKET "
    
}
response = order(**params)  
print(response)

#stop LIMIT
params = {
    "symbol": pairs,
    "side": "SELL",
    "price": stop_price,
    "type": "STOP",
    "quantity": quentity,
    "timeInForce": "GTC", 
    "stopPrice":stop_price,
    "closePosition":"STOP_MARKET "
    
}
response = order(**params) 
print(response)

#TAKE PROFIT MARKEY
params = {
    "symbol": pairs,
    "side": "SELL",
   # "price": 150,
    "type": "TAKE_PROFIT_MARKET",
    "quantity": quentity,
    "timeInForce": "GTC", 
    "stopPrice":take_profit_price,
    "closePosition":"TAKE_PROFIT_MARKET "
    
}
response = order(**params) 
print(response)
#TAKE PROFITE LIMIT
params = {
    "symbol": pairs,
    "side": "SELL",
    "price": take_profit_price,
    "type": "TAKE_PROFIT",
    "quantity": quentity,
    "timeInForce": "GTC", 
    "stopPrice":take_profit_price,
    "closePosition":"TAKE_PROFIT"
    
}


response = order(**params)  
print(response)
`

**Comment by 2pd** [comment]
this is not an issue of the library/
