### ISSUE TITLE
can't cancel open order

### ISSUE THREAD

**Issue by Buki5** [Binance-docs/binance-futures-connector-python#63]
Hello,
I am trying to use the cancel order func and just keep getting this error msg: 
ERROR:root:Found error. status: 400, error code: -2011, error message: Unknown order sent.

I did everyting correctly,
the order just opened, not filled....

I looked all over the web and didn't found anything....

um_futures_client = UMFutures(base_url="https://testnet.binancefuture.com", key=key, secret=secret)
    try:
        response = um_futures_client.cancel_order(
            symbol=symbol, orderId=orderId, recvWindow=recvWindow,
        )
        logging.info(response)
        # print(response)
        return response["status"]
    except ClientError as error:
        logging.error(
            "Found error. status: {}, error code: {}, error message: {}".format(
                error.status_code, error.error_code, error.error_message
            )
        )

**Comment by 2pd** [comment]
Please refer to this topic https://dev.binance.vision/t/how-to-debug-the-error-2011-unknown-order-sent-when-trying-to-cancel-an-open-order/14003
for this error.
