### ISSUE TITLE
‘Unknown order sent’ while trying to cancel order

### ISSUE THREAD

**Issue by hilmiazizi** [Binance-docs/binance-futures-connector-python#8]
i can't cancel an open order
here is response from get_orders()

`[{'orderId': 1896063477, 'symbol': 'HOTUSDT', 'status': 'NEW', 'clientOrderId': 'Tsar_TP', 'price': '0', 'avgPrice': '0', 'origQty': '0', 'executedQty': '0', 'cumQuote': '0', 'timeInForce': 'GTC', 'type': 'TAKE_PROFIT_MARKET', 'reduceOnly': True, 'closePosition': True, 'side': 'SELL', 'positionSide': 'BOTH', 'stopPrice': '0.006007', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'TAKE_PROFIT_MARKET', 'time': 1641826768523, 'updateTime': 1641826768523}]`

and here is my cancel order post data:
`{'symbol': 'HOTUSDT', 'orderId': 1896063477}`
the response is 400, -2011, 'Unknown order sent.'

i’ve been trying to use orderId and origClientOrderId but still have same response, trying to fill timestamp but still the same.
THE ORDER IS STILL OPEN AND NOT FILLED AT ALL

**Comment by Eugen7887** [comment]
You need to correct the condition to "is not None"
https://github.com/Binance-docs/binance-futures-connector-python/blob/d820b73a15e9f64c80891a13694ca0c5d1693b90/binance/futures/account.py#L265

Warning!
This error is repeated in several places...

**Comment by YuenHoilong** [comment]
You need to provide both orderId and origClientOrderId to cancel_order().

**Comment by hilmiazizi** [comment]
> You need to specify both orderId and origClientOrderId to cancel_order().

still same

**Comment by hilmiazizi** [comment]
> You need to correct the condition to "is not None"
> 
> https://github.com/Binance-docs/binance-futures-connector-python/blob/d820b73a15e9f64c80891a13694ca0c5d1693b90/binance/futures/account.py#L265
> 
> Warning! This error is repeated in several places...

fixed! thanks

**Comment by ronekarleone** [comment]
This function look like this:
 ```
def query_order(self, symbol: str, orderId: int = None, origClientOrderId: str = None, **kwargs):
  if (orderId is None) and (origClientOrderId is None):
          check_required_parameters([[symbol, "symbol"], [orderId, "orderId"], ["origClientOrderId", origClientOrderId]])
      elif (orderId is None):
          params = {"symbol": symbol, "orderId": orderId, **kwargs}
      else:
          params = {"symbol": symbol, "origClientOrderId": origClientOrderId, **kwargs}
  url_path = "/fapi/v1/order"
  return self.sign_request("GET", url_path, params)
```
And of course there is an error in the condition: `orderId is None`.

But if you specify orderId and origClientOrderId parameters, then the else will work, so origClientOrderId will sent in request.
So use like this:
`response_cancel_order = client.cancel_order(symbol="BTCUSDT", orderId=1232453, origClientOrderId=2d3d4t2332432, recvWindow=2000)`
And this solution works for me.

**Comment by andrea-c-binance** [comment]
Hi all, thanks for the feedback! this issue is fixed, you can pass either orderId or clientOrderId now, thanks.
